DELETE FROM public.categorias;

INSERT INTO public.categorias (id, nome, icone, cor, forma_pagamento, parent_id, user_id) VALUES
('moradia', 'Moradia', '🏠', 'hsl(210, 70%, 50%)', NULL, NULL, NULL),
('aluguel_financiamento', 'Aluguel ou financiamento', '🏡', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('condominio', 'Condomínio', '🏢', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('agua_luz_gas', 'Água, luz, gás', '💡', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('internet', 'Internet', '📶', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('manutencao_casa', 'Manutenção da casa', '🛠️', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('seguro_residencial', 'Seguro residencial', '🛡️', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('iptu', 'IPTU', '🧾', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),

('alimentacao', 'Alimentação', '🍔', 'hsl(30, 95%, 55%)', NULL, NULL, NULL),
('supermercado', 'Supermercado', '🛒', 'hsl(30, 95%, 55%)', NULL, 'alimentacao', NULL),
('restaurantes_delivery', 'Restaurantes e delivery', '🍽️', 'hsl(30, 95%, 55%)', NULL, 'alimentacao', NULL),
('lanches_cafes', 'Lanches e cafés', '☕', 'hsl(30, 95%, 55%)', NULL, 'alimentacao', NULL),
('bebidas', 'Bebidas', '🍷', 'hsl(30, 95%, 55%)', NULL, 'alimentacao', NULL),
('alimentacao_trabalho', 'Alimentação fora de casa no trabalho', '💼', 'hsl(30, 95%, 55%)', NULL, 'alimentacao', NULL),

('transporte', 'Transporte', '🚗', 'hsl(225, 70%, 55%)', NULL, NULL, NULL),
('combustivel', 'Combustível', '⛽', 'hsl(225, 70%, 55%)', NULL, 'transporte', NULL),
('transporte_publico', 'Transporte público', '🚌', 'hsl(225, 70%, 55%)', NULL, 'transporte', NULL),
('manutencao_veiculo', 'Manutenção do veículo', '🔧', 'hsl(225, 70%, 55%)', NULL, 'transporte', NULL),
('apps_transporte', 'Aplicativos de transporte', '🚕', 'hsl(225, 70%, 55%)', NULL, 'transporte', NULL),
('estacionamento_pedagios', 'Estacionamento e pedágios', '🅿️', 'hsl(225, 70%, 55%)', NULL, 'transporte', NULL),
('transporte_escolar', 'Transporte escolar ou fretado', '🎒', 'hsl(225, 70%, 55%)', NULL, 'transporte', NULL),

('saude', 'Saúde', '❤️', 'hsl(0, 60%, 70%)', NULL, NULL, NULL),
('plano_saude', 'Plano de saúde', '🏥', 'hsl(0, 60%, 70%)', NULL, 'saude', NULL),
('consultas_medicas', 'Consultas médicas', '👩‍⚕️', 'hsl(0, 60%, 70%)', NULL, 'saude', NULL),
('medicamentos', 'Medicamentos', '💊', 'hsl(0, 60%, 70%)', NULL, 'saude', NULL),
('exames_laboratoriais', 'Exames laboratoriais', '🔬', 'hsl(0, 60%, 70%)', NULL, 'saude', NULL),
('terapias', 'Terapias', '🧘‍♀️', 'hsl(0, 60%, 70%)', NULL, 'saude', NULL),
('academias', 'Academias e atividades físicas', '💪', 'hsl(0, 60%, 70%)', NULL, 'saude', NULL),

('educacao', 'Educação', '🎓', 'hsl(200, 70%, 50%)', NULL, NULL, NULL),
('mensalidades_escolares', 'Mensalidades escolares ou universitárias', '📚', 'hsl(200, 70%, 50%)', NULL, 'educacao', NULL),
('cursos_workshops', 'Cursos e workshops', '🧑‍💻', 'hsl(200, 70%, 50%)', NULL, 'educacao', NULL),
('livros_materiais', 'Livros e materiais de estudo', '📖', 'hsl(200, 70%, 50%)', NULL, 'educacao', NULL),
('material_escolar', 'Material escolar', '✏️', 'hsl(200, 70%, 50%)', NULL, 'educacao', NULL),
('cursos_online', 'Cursos online / assinatura de plataformas', '💻', 'hsl(200, 70%, 50%)', NULL, 'educacao', NULL),

('lazer_entretenimento', 'Lazer e Entretenimento', '🎉', 'hsl(280, 70%, 55%)', NULL, NULL, NULL),
('cinema_teatro_shows', 'Cinema, teatro, shows', '🎭', 'hsl(280, 70%, 55%)', NULL, 'lazer_entretenimento', NULL),
('streaming', 'Streaming', '📺', 'hsl(280, 70%, 55%)', NULL, 'lazer_entretenimento', NULL),
('viagens_passeios', 'Viagens e passeios', '✈️', 'hsl(280, 70%, 55%)', NULL, 'lazer_entretenimento', NULL),
('hobbies', 'Hobbies', '🎨', 'hsl(280, 70%, 55%)', NULL, 'lazer_entretenimento', NULL),
('jogos', 'Jogos', '🎮', 'hsl(280, 70%, 55%)', NULL, 'lazer_entretenimento', NULL),

('compras_vestuario', 'Compras e vestuário', '🛍️', 'hsl(330, 70%, 55%)', NULL, NULL, NULL),
('roupas_calcados', 'Roupas e calçados', '👕', 'hsl(330, 70%, 55%)', NULL, 'compras_vestuario', NULL),
('cosmeticos_cuidados', 'Cosméticos e cuidados pessoais', '💄', 'hsl(330, 70%, 55%)', NULL, 'compras_vestuario', NULL),
('acessorios', 'Acessórios', '💍', 'hsl(330, 70%, 55%)', NULL, 'compras_vestuario', NULL),
('eletronicos_gadgets', 'Eletrônicos e gadgets', '📱', 'hsl(330, 70%, 55%)', NULL, 'compras_vestuario', NULL),

('financas_dividas', 'Finanças e dívidas', '💰', 'hsl(150, 60%, 45%)', NULL, NULL, NULL),
('cartao_credito', 'Cartão de crédito', '💳', 'hsl(150, 60%, 45%)', 'credit', 'financas_dividas', NULL),
('emprestimos', 'Empréstimos', '💸', 'hsl(150, 60%, 45%)', NULL, 'financas_dividas', NULL),
('investimentos', 'Investimentos', '📈', 'hsl(150, 60%, 45%)', NULL, 'financas_dividas', NULL),
('poupanca_reservas', 'Poupança / reservas financeiras', '🏦', 'hsl(150, 60%, 45%)', NULL, 'financas_dividas', NULL),
('taxas_juros', 'Taxas bancárias e juros', '📊', 'hsl(150, 60%, 45%)', NULL, 'financas_dividas', NULL),

('familia_filhos', 'Família', '👨‍👩‍👧‍👦', 'hsl(345, 75%, 60%)', NULL, NULL, NULL),
('creche_baba', 'Creche ou babá', '👶', 'hsl(345, 75%, 60%)', NULL, 'familia_filhos', NULL),
('atividades_extracurriculares', 'Atividades extracurriculares', '⚽', 'hsl(345, 75%, 60%)', NULL, 'familia_filhos', NULL),
('roupas_material_filhos', 'Roupas e material escolar', '🧸', 'hsl(345, 75%, 60%)', NULL, 'familia_filhos', NULL),
('presentes_filhos', 'Presentes de aniversário ou datas comemorativas', '🎁', 'hsl(345, 75%, 60%)', NULL, 'familia_filhos', NULL),

('pets', 'Pets', '🐾', 'hsl(75, 60%, 50%)', NULL, NULL, NULL),
('alimentacao_pets', 'Alimentação', '🍖', 'hsl(75, 60%, 50%)', NULL, 'pets', NULL),
('vacinas_veterinario', 'Vacinas e consultas veterinárias', '🩺', 'hsl(75, 60%, 50%)', NULL, 'pets', NULL),
('banho_tosa', 'Banho e tosa', '🛁', 'hsl(75, 60%, 50%)', NULL, 'pets', NULL),
('pet_shop_acessorios', 'Pet shop / acessórios', '🦴', 'hsl(75, 60%, 50%)', NULL, 'pets', NULL),

('seguros_servicos', 'Seguros e serviços', '📄', 'hsl(40, 70%, 50%)', NULL, NULL, NULL),
('seguro_vida', 'Seguro de vida', '💖', 'hsl(40, 70%, 50%)', NULL, 'seguros_servicos', NULL),
('seguro_carro', 'Seguro do carro', '🚗', 'hsl(40, 70%, 50%)', NULL, 'seguros_servicos', NULL),
('servicos_assinatura', 'Serviços de assinatura', '💳', 'hsl(40, 70%, 50%)', NULL, 'seguros_servicos', NULL),

('outros_diversos', 'Outros / Diversos', '📦', 'hsl(215, 15%, 50%)', NULL, NULL, NULL),
('presentes_diversos', 'Presentes', '🎁', 'hsl(215, 15%, 50%)', NULL, 'outros_diversos', NULL),
('doacoes', 'Doações', '🤲', 'hsl(215, 15%, 50%)', NULL, 'outros_diversos', NULL),
('gastos_inesperados', 'Gastos inesperados / emergências', '🚨', 'hsl(215, 15%, 50%)', NULL, 'outros_diversos', NULL),
('multas_taxas', 'Multas e taxas eventuais', '⚠️', 'hsl(215, 15%, 50%)', NULL, 'outros_diversos', NULL),

('salary', 'Salário', '💰', 'hsl(150, 60%, 45%)', NULL, NULL, NULL),
('investment_income', 'Rendimento de Investimento', '📈', 'hsl(150, 65%, 55%)', NULL, NULL, NULL),
('other_income', 'Outras Receitas', '💸', 'hsl(165, 65%, 50%)', NULL, NULL, NULL);