DELETE FROM public.categorias WHERE user_id IS NULL;

INSERT INTO public.categorias (id, nome, icone, cor, forma_pagamento, parent_id, user_id) VALUES
('moradia', 'Moradia', '🏠', 'hsl(210, 70%, 50%)', NULL, NULL, NULL),
('moradia_aluguel', 'Aluguel', '🏠', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('moradia_condominio', 'Condomínio', '🏢', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('moradia_financiamento', 'Financiamento imobiliário', '🏡', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('moradia_agua', 'Água', '🚰', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('moradia_luz', 'Luz', '💡', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('moradia_gas', 'Gás', '🔥', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('moradia_internet', 'Internet', '🌐', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('moradia_manutencao', 'Manutenção / Reparos', '🛠️', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('moradia_moveis', 'Móveis e utensílios', '🛋️', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),
('moradia_iptu', 'IPTU', '🧾', 'hsl(210, 70%, 50%)', NULL, 'moradia', NULL),

('transporte', 'Transporte', '🚗', 'hsl(225, 70%, 55%)', NULL, NULL, NULL),
('transporte_combustivel', 'Combustível', '⛽', 'hsl(225, 70%, 55%)', NULL, 'transporte', NULL),
('transporte_manutencao', 'Manutenção do veículo', '🔧', 'hsl(225, 70%, 55%)', NULL, 'transporte', NULL),
('transporte_seguro', 'Seguro', '🛡️', 'hsl(225, 70%, 55%)', NULL, 'transporte', NULL),
('transporte_estacionamento', 'Estacionamento', '🅿️', 'hsl(225, 70%, 55%)', NULL, 'transporte', NULL),
('transporte_publico', 'Transporte público', '🚌', 'hsl(225, 70%, 55%)', NULL, 'transporte', NULL),
('transporte_apps', 'Apps (Uber, 99...)', '🚕', 'hsl(225, 70%, 55%)', NULL, 'transporte', NULL),
('transporte_pedagio', 'Pedágio', '🚧', 'hsl(225, 70%, 55%)', NULL, 'transporte', NULL),
('transporte_financiamento', 'Financiamento de veículo', '🚗', 'hsl(225, 70%, 55%)', NULL, 'transporte', NULL),

('alimentacao', 'Alimentação', '🍽️', 'hsl(30, 95%, 55%)', NULL, NULL, NULL),
('alimentacao_supermercado', 'Supermercado', '🛒', 'hsl(30, 95%, 55%)', NULL, 'alimentacao', NULL),
('alimentacao_padaria', 'Padaria', '🍞', 'hsl(30, 95%, 55%)', NULL, 'alimentacao', NULL),
('alimentacao_restaurante', 'Restaurante', '🍽️', 'hsl(30, 95%, 55%)', NULL, 'alimentacao', NULL),
('alimentacao_delivery', 'Delivery', '📦', 'hsl(30, 95%, 55%)', NULL, 'alimentacao', NULL),
('alimentacao_lanches', 'Lanches', '🍔', 'hsl(30, 95%, 55%)', NULL, 'alimentacao', NULL),

('saude', 'Saúde', '🏥', 'hsl(0, 60%, 70%)', NULL, NULL, NULL),
('saude_plano', 'Plano de saúde', '🩺', 'hsl(0, 60%, 70%)', NULL, 'saude', NULL),
('saude_medicamentos', 'Medicamentos', '💊', 'hsl(0, 60%, 70%)', NULL, 'saude', NULL),
('saude_consultas', 'Consultas', '👨‍⚕️', 'hsl(0, 60%, 70%)', NULL, 'saude', NULL),
('saude_exames', 'Exames', '🧪', 'hsl(0, 60%, 70%)', NULL, 'saude', NULL),
('saude_academia', 'Academia', '🏋️', 'hsl(0, 60%, 70%)', NULL, 'saude', NULL),
('saude_terapia', 'Terapia', '🧠', 'hsl(0, 60%, 70%)', NULL, 'saude', NULL),

('educacao', 'Educação', '🎓', 'hsl(200, 70%, 50%)', NULL, NULL, NULL),
('educacao_mensalidade', 'Mensalidade', '🏫', 'hsl(200, 70%, 50%)', NULL, 'educacao', NULL),
('educacao_cursos', 'Cursos', '💻', 'hsl(200, 70%, 50%)', NULL, 'educacao', NULL),
('educacao_livros', 'Livros', '📚', 'hsl(200, 70%, 50%)', NULL, 'educacao', NULL),
('educacao_workshops', 'Workshops / Eventos', '🎟️', 'hsl(200, 70%, 50%)', NULL, 'educacao', NULL),

('lazer', 'Lazer', '🎉', 'hsl(280, 70%, 55%)', NULL, NULL, NULL),
('lazer_cinema', 'Cinema', '🎬', 'hsl(280, 70%, 55%)', NULL, 'lazer', NULL),
('lazer_viagens', 'Viagens', '✈️', 'hsl(280, 70%, 55%)', NULL, 'lazer', NULL),
('lazer_passeios', 'Passeios', '🎡', 'hsl(280, 70%, 55%)', NULL, 'lazer', NULL),
('lazer_streaming', 'Streaming', '📺', 'hsl(280, 70%, 55%)', NULL, 'lazer', NULL),
('lazer_hobbies', 'Hobbies', '🎨', 'hsl(280, 70%, 55%)', NULL, 'lazer', NULL),

('pessoais', 'Pessoais', '👕', 'hsl(330, 70%, 55%)', NULL, NULL, NULL),
('pessoais_roupas', 'Roupas', '👗', 'hsl(330, 70%, 55%)', NULL, 'pessoais', NULL),
('pessoais_cuidados', 'Cuidados pessoais', '💅', 'hsl(330, 70%, 55%)', NULL, 'pessoais', NULL),
('pessoais_presentes', 'Presentes', '🎁', 'hsl(330, 70%, 55%)', NULL, 'pessoais', NULL),
('pessoais_assinaturas', 'Assinaturas', '📦', 'hsl(330, 70%, 55%)', NULL, 'pessoais', NULL),

('obrigacoes_financeiras', 'Obrigações Financeiras', '🧾', 'hsl(40, 70%, 50%)', NULL, NULL, NULL),
('obrigacoes_impostos', 'Impostos', '🏛️', 'hsl(40, 70%, 50%)', NULL, 'obrigacoes_financeiras', NULL),
('obrigacoes_multas', 'Multas', '⚠️', 'hsl(40, 70%, 50%)', NULL, 'obrigacoes_financeiras', NULL),
('obrigacoes_tarifas_bancarias', 'Tarifas bancárias', '🏦', 'hsl(40, 70%, 50%)', NULL, 'obrigacoes_financeiras', NULL),
('obrigacoes_juros', 'Juros', '📉', 'hsl(40, 70%, 50%)', NULL, 'obrigacoes_financeiras', NULL),
('obrigacoes_cartao_credito', 'Cartão de crédito', '💳', 'hsl(40, 70%, 50%)', 'credit', 'obrigacoes_financeiras', NULL),
('obrigacoes_dividas', 'Dívidas', '💣', 'hsl(40, 70%, 50%)', NULL, 'obrigacoes_financeiras', NULL),
('obrigacoes_emprestimos_pessoais', 'Empréstimos pessoais', '📄', 'hsl(40, 70%, 50%)', NULL, 'obrigacoes_financeiras', NULL),
('obrigacoes_emprestimo_bancario', 'Empréstimo bancário', '🏦', 'hsl(40, 70%, 50%)', NULL, 'obrigacoes_financeiras', NULL),
('obrigacoes_emprestimo', 'Empréstimo', '🤝', 'hsl(40, 70%, 50%)', NULL, 'obrigacoes_financeiras', NULL),
('obrigacoes_dividas_cartao_credito', 'Dívidas do cartão de crédito', '💳', 'hsl(40, 70%, 50%)', NULL, 'obrigacoes_financeiras', NULL),
('obrigacoes_renegociacao', 'Renegociação / Parcelamentos', '🔄', 'hsl(40, 70%, 50%)', NULL, 'obrigacoes_financeiras', NULL),
('obrigacoes_atrasos', 'Atrasos / Contas vencidas', '❗', 'hsl(40, 70%, 50%)', NULL, 'obrigacoes_financeiras', NULL),

('investimentos', 'Investimentos', '💹', 'hsl(150, 60%, 45%)', NULL, NULL, NULL),
('investimentos_acoes', 'Ações', '📈', 'hsl(150, 60%, 45%)', NULL, 'investimentos', NULL),
('investimentos_fundos', 'Fundos', '💼', 'hsl(150, 60%, 45%)', NULL, 'investimentos', NULL),
('investimentos_tesouro', 'Tesouro', '🏦', 'hsl(150, 60%, 45%)', NULL, 'investimentos', NULL),
('investimentos_criptomoedas', 'Criptomoedas', '🪙', 'hsl(150, 60%, 45%)', NULL, 'investimentos', NULL),
('investimentos_poupanca', 'Poupança', '💰', 'hsl(150, 60%, 45%)', NULL, 'investimentos', NULL),
('investimentos_fii', 'Fundo Imobiliário (FIIs)', '🏢', 'hsl(150, 60%, 45%)', NULL, 'investimentos', NULL),
('investimentos_aportes_resgates', 'Aportes / Resgates', '➕', 'hsl(150, 60%, 45%)', NULL, 'investimentos', NULL),

('trabalho_negocio', 'Trabalho / Negócio', '💼', 'hsl(255, 65%, 60%)', NULL, NULL, NULL),
('trabalho_ferramentas', 'Ferramentas / Softwares', '🛠️', 'hsl(255, 65%, 60%)', NULL, 'trabalho_negocio', NULL),
('trabalho_materiais', 'Materiais', '📦', 'hsl(255, 65%, 60%)', NULL, 'trabalho_negocio', NULL),
('trabalho_servicos', 'Serviços contratados', '🤝', 'hsl(255, 65%, 60%)', NULL, 'trabalho_negocio', NULL),
('trabalho_marketing', 'Marketing', '📣', 'hsl(255, 65%, 60%)', NULL, 'trabalho_negocio', NULL),
('trabalho_equipamentos', 'Equipamentos', '💻', 'hsl(255, 65%, 60%)', NULL, 'trabalho_negocio', NULL),

('receitas', 'Receitas', '💵', 'hsl(150, 65%, 55%)', NULL, NULL, NULL),
('receitas_salario', 'Salário', '💼', 'hsl(150, 65%, 55%)', NULL, 'receitas', NULL),
('receitas_rendimentos', 'Rendimentos', '📉', 'hsl(150, 65%, 55%)', NULL, 'receitas', NULL),
('receitas_extras', 'Receitas extras', '💸', 'hsl(150, 65%, 55%)', NULL, 'receitas', NULL),
('receitas_reembolsos', 'Reembolsos', '🔁', 'hsl(150, 65%, 55%)', NULL, 'receitas', NULL),
('receitas_venda_bens', 'Venda de bens', '🛍️', 'hsl(150, 65%, 55%)', NULL, 'receitas', NULL),
('receitas_dividendos', 'Dividendos', '💰', 'hsl(150, 65%, 55%)', NULL, 'receitas', NULL),
('receitas_aluguel_imoveis', 'Aluguel de imóveis', '🏘️', 'hsl(150, 65%, 55%)', NULL, 'receitas', NULL),
('receitas_cofrinho', 'Cofrinho', '🐷', 'hsl(150, 65%, 55%)', NULL, 'receitas', NULL),

('familia_filhos', 'Família', '👨‍👩‍👧', 'hsl(345, 75%, 60%)', NULL, NULL, NULL),
('familia_atividades_extracurriculares', 'Atividades extracurriculares', '🧩', 'hsl(345, 75%, 60%)', NULL, 'familia_filhos', NULL),
('familia_creche_baba', 'Creche ou babá', '👶', 'hsl(345, 75%, 60%)', NULL, 'familia_filhos', NULL),
('familia_presentes_aniversario', 'Presentes de aniversário ou datas comemorativas', '🎁', 'hsl(345, 75%, 60%)', NULL, 'familia_filhos', NULL),
('familia_roupas_material_escolar', 'Roupas e material escolar', '🎒', 'hsl(345, 75%, 60%)', NULL, 'familia_filhos', NULL);