INSERT INTO public.categorias (id, nome, icone, cor, forma_pagamento, user_id, parent_id) VALUES
('moradia', 'Moradia', '🏠', 'hsl(210, 70%, 50%)', NULL, NULL, NULL),
('moradia_aluguel', 'Aluguel', '🏠', 'hsl(210, 70%, 50%)', NULL, NULL, 'moradia'),
('moradia_condominio', 'Condomínio', '🏢', 'hsl(210, 70%, 50%)', NULL, NULL, 'moradia'),
('moradia_financiamento', 'Financiamento imobiliário', '🏡', 'hsl(210, 70%, 50%)', NULL, NULL, 'moradia'),
('moradia_agua', 'Água', '🚰', 'hsl(210, 70%, 50%)', NULL, NULL, 'moradia'),
('moradia_luz', 'Luz', '💡', 'hsl(210, 70%, 50%)', NULL, NULL, 'moradia'),
('moradia_gas', 'Gás', '🔥', 'hsl(210, 70%, 50%)', NULL, NULL, 'moradia'),
('moradia_internet', 'Internet', '🌐', 'hsl(210, 70%, 50%)', NULL, NULL, 'moradia'),
('moradia_manutencao', 'Manutenção / Reparos', '🛠️', 'hsl(210, 70%, 50%)', NULL, NULL, 'moradia'),
('moradia_moveis', 'Móveis e utensílios', '🛋️', 'hsl(210, 70%, 50%)', NULL, NULL, 'moradia'),
('moradia_iptu', 'IPTU', '🧾', 'hsl(210, 70%, 50%)', NULL, NULL, 'moradia'),
('transporte', 'Transporte', '🚗', 'hsl(225, 70%, 55%)', NULL, NULL, NULL),
('transporte_combustivel', 'Combustível', '⛽', 'hsl(225, 70%, 55%)', NULL, NULL, 'transporte'),
('transporte_manutencao', 'Manutenção do veículo', '🔧', 'hsl(225, 70%, 55%)', NULL, NULL, 'transporte'),
('transporte_seguro', 'Seguro', '🛡️', 'hsl(225, 70%, 55%)', NULL, NULL, 'transporte'),
('transporte_estacionamento', 'Estacionamento', '🅿️', 'hsl(225, 70%, 55%)', NULL, NULL, 'transporte'),
('transporte_publico', 'Transporte público', '🚌', 'hsl(225, 70%, 55%)', NULL, NULL, 'transporte'),
('transporte_apps', 'Apps (Uber, 99...)', '🚕', 'hsl(225, 70%, 55%)', NULL, NULL, 'transporte'),
('transporte_pedagio', 'Pedágio', '🚧', 'hsl(225, 70%, 55%)', NULL, NULL, 'transporte'),
('transporte_financiamento', 'Financiamento de veículo', '🚗', 'hsl(225, 70%, 55%)', NULL, NULL, 'transporte'),
('alimentacao', 'Alimentação', '🍽️', 'hsl(30, 95%, 55%)', NULL, NULL, NULL),
('alimentacao_supermercado', 'Supermercado', '🛒', 'hsl(30, 95%, 55%)', NULL, NULL, 'alimentacao'),
('alimentacao_padaria', 'Padaria', '🍞', 'hsl(30, 95%, 55%)', NULL, NULL, 'alimentacao'),
('alimentacao_restaurante', 'Restaurante', '🍽️', 'hsl(30, 95%, 55%)', NULL, NULL, 'alimentacao'),
('alimentacao_delivery', 'Delivery', '📦', 'hsl(30, 95%, 55%)', NULL, NULL, 'alimentacao'),
('alimentacao_lanches', 'Lanches', '🍔', 'hsl(30, 95%, 55%)', NULL, NULL, 'alimentacao'),
('saude', 'Saúde', '🏥', 'hsl(0, 60%, 70%)', NULL, NULL, NULL),
('saude_plano', 'Plano de saúde', '🩺', 'hsl(0, 60%, 70%)', NULL, NULL, 'saude'),
('saude_medicamentos', 'Medicamentos', '💊', 'hsl(0, 60%, 70%)', NULL, NULL, 'saude'),
('saude_consultas', 'Consultas', '👨‍⚕️', 'hsl(0, 60%, 70%)', NULL, NULL, 'saude'),
('saude_exames', 'Exames', '🧪', 'hsl(0, 60%, 70%)', NULL, NULL, 'saude'),
('saude_academia', 'Academia', '🏋️', 'hsl(0, 60%, 70%)', NULL, NULL, 'saude'),
('saude_terapia', 'Terapia', '🧠', 'hsl(0, 60%, 70%)', NULL, NULL, 'saude'),
('educacao', 'Educação', '🎓', 'hsl(200, 70%, 50%)', NULL, NULL, NULL),
('educacao_mensalidade', 'Mensalidade', '🏫', 'hsl(200, 70%, 50%)', NULL, NULL, 'educacao'),
('educacao_cursos', 'Cursos', '💻', 'hsl(200, 70%, 50%)', NULL, NULL, 'educacao'),
('educacao_livros', 'Livros', '📚', 'hsl(200, 70%, 50%)', NULL, NULL, 'educacao'),
('educacao_workshops', 'Workshops / Eventos', '🎟️', 'hsl(200, 70%, 50%)', NULL, NULL, 'educacao'),
('lazer', 'Lazer', '🎉', 'hsl(280, 70%, 55%)', NULL, NULL, NULL),
('lazer_cinema', 'Cinema', '🎬', 'hsl(280, 70%, 55%)', NULL, NULL, 'lazer'),
('lazer_viagens', 'Viagens', '✈️', 'hsl(280, 70%, 55%)', NULL, NULL, 'lazer'),
('lazer_passeios', 'Passeios', '🎡', 'hsl(280, 70%, 55%)', NULL, NULL, 'lazer'),
('lazer_streaming', 'Streaming', '📺', 'hsl(280, 70%, 55%)', NULL, NULL, 'lazer'),
('lazer_hobbies', 'Hobbies', '🎨', 'hsl(280, 70%, 55%)', NULL, NULL, 'lazer'),
('pessoais', 'Pessoais', '👕', 'hsl(330, 70%, 55%)', NULL, NULL, NULL),
('pessoais_roupas', 'Roupas', '👗', 'hsl(330, 70%, 55%)', NULL, NULL, 'pessoais'),
('pessoais_cuidados', 'Cuidados pessoais', '💅', 'hsl(330, 70%, 55%)', NULL, NULL, 'pessoais'),
('pessoais_presentes', 'Presentes', '🎁', 'hsl(330, 70%, 55%)', NULL, NULL, 'pessoais'),
('pessoais_assinaturas', 'Assinaturas', '📦', 'hsl(330, 70%, 55%)', NULL, NULL, 'pessoais'),
('obrigacoes_financeiras', 'Obrigações Financeiras', '🧾', 'hsl(40, 70%, 50%)', NULL, NULL, NULL),
('obrigacoes_impostos', 'Impostos', '🏛️', 'hsl(40, 70%, 50%)', NULL, NULL, 'obrigacoes_financeiras'),
('obrigacoes_multas', 'Multas', '⚠️', 'hsl(40, 70%, 50%)', NULL, NULL, 'obrigacoes_financeiras'),
('obrigacoes_tarifas_bancarias', 'Tarifas bancárias', '🏦', 'hsl(40, 70%, 50%)', NULL, NULL, 'obrigacoes_financeiras'),
('obrigacoes_juros', 'Juros', '📉', 'hsl(40, 70%, 50%)', NULL, NULL, 'obrigacoes_financeiras'),
('obrigacoes_cartao_credito', 'Cartão de crédito', '💳', 'hsl(40, 70%, 50%)', 'credit', NULL, 'obrigacoes_financeiras'),
('obrigacoes_dividas', 'Dívidas', '💣', 'hsl(40, 70%, 50%)', NULL, NULL, 'obrigacoes_financeiras'),
('obrigacoes_emprestimos_pessoais', 'Empréstimos pessoais', '📄', 'hsl(40, 70%, 50%)', NULL, NULL, 'obrigacoes_financeiras'),
('obrigacoes_emprestimo_bancario', 'Empréstimo bancário', '🏦', 'hsl(40, 70%, 50%)', NULL, NULL, 'obrigacoes_financeiras'),
('obrigacoes_emprestimo', 'Empréstimo', '🤝', 'hsl(40, 70%, 50%)', NULL, NULL, 'obrigacoes_financeiras'),
('obrigacoes_dividas_cartao_credito', 'Dívidas do cartão de crédito', '💳', 'hsl(40, 70%, 50%)', NULL, NULL, 'obrigacoes_financeiras'),
('obrigacoes_renegociacao', 'Renegociação / Parcelamentos', '🔄', 'hsl(40, 70%, 50%)', NULL, NULL, 'obrigacoes_financeiras'),
('obrigacoes_atrasos', 'Atrasos / Contas vencidas', '❗', 'hsl(40, 70%, 50%)', NULL, NULL, 'obrigacoes_financeiras'),
('trabalho_negocio', 'Trabalho / Negócio', '💼', 'hsl(255, 65%, 60%)', NULL, NULL, NULL),
('trabalho_ferramentas', 'Ferramentas / Softwares', '🛠️', 'hsl(255, 65%, 60%)', NULL, NULL, 'trabalho_negocio'),
('trabalho_materiais', 'Materiais', '📦', 'hsl(255, 65%, 60%)', NULL, NULL, 'trabalho_negocio'),
('trabalho_servicos', 'Serviços contratados', '🤝', 'hsl(255, 65%, 60%)', NULL, NULL, 'trabalho_negocio'),
('trabalho_marketing', 'Marketing', '📣', 'hsl(255, 65%, 60%)', NULL, NULL, 'trabalho_negocio'),
('trabalho_equipamentos', 'Equipamentos', '💻', 'hsl(255, 65%, 60%)', NULL, NULL, 'trabalho_negocio'),
('familia_filhos', 'Família e Filhos', '👨‍👩‍👧', 'hsl(345, 75%, 60%)', NULL, NULL, NULL),
('familia_atividades_extracurriculares', 'Atividades extracurriculares', '🧩', 'hsl(345, 75%, 60%)', NULL, NULL, 'familia_filhos'),
('familia_creche_baba', 'Creche ou babá', '👶', 'hsl(345, 75%, 60%)', NULL, NULL, 'familia_filhos'),
('familia_presentes_aniversario', 'Presentes de aniversário ou datas comemorativas', '🎁', 'hsl(345, 75%, 60%)', NULL, NULL, 'familia_filhos'),
('familia_roupas_material_escolar', 'Roupas e material escolar', '🎒', 'hsl(345, 75%, 60%)', NULL, NULL, 'familia_filhos'),
('receitas_e_investimentos', 'Receitas e Investimentos', '💵', 'hsl(150, 65%, 55%)', NULL, NULL, NULL),
('receitas_e_investimentos_salario', 'Salário', '💼', 'hsl(150, 65%, 55%)', NULL, NULL, 'receitas_e_investimentos'),
('receitas_e_investimentos_acoes', 'Ações (dividendos, venda de ações)', '📈', 'hsl(150, 65%, 55%)', NULL, NULL, 'receitas_e_investimentos'),
('receitas_e_investimentos_fundos', 'Fundos (rendimentos de fundos)', '💼', 'hsl(150, 65%, 55%)', NULL, NULL, 'receitas_e_investimentos'),
('receitas_e_investimentos_tesouro', 'Tesouro (juros, resgates)', '🏦', 'hsl(150, 65%, 55%)', NULL, NULL, 'receitas_e_investimentos'),
('receitas_e_investimentos_criptomoedas', 'Criptomoedas (lucros, vendas)', '🪙', 'hsl(150, 65%, 55%)', NULL, NULL, 'receitas_e_investimentos'),
('receitas_e_investimentos_poupanca', 'Poupança (rendimentos, resgates)', '💰', 'hsl(150, 65%, 55%)', NULL, NULL, 'receitas_e_investimentos'),
('receitas_e_investimentos_dividendos', 'Dividendos', '💰', 'hsl(150, 65%, 55%)', NULL, NULL, 'receitas_e_investimentos'),
('receitas_e_investimentos_aportes', 'Aportes (entrada de capital)', '➕', 'hsl(150, 65%, 55%)', NULL, NULL, 'receitas_e_investimentos'),
('receitas_e_investimentos_reembolsos', 'Reembolsos', '🔁', 'hsl(150, 65%, 55%)', NULL, NULL, 'receitas_e_investimentos'),
('receitas_e_investimentos_extras', 'Receitas Extras', '💸', 'hsl(150, 65%, 55%)', NULL, NULL, 'receitas_e_investimentos'),
('receitas_e_investimentos_juros_capital', 'Juros sobre capital', '📉', 'hsl(150, 65%, 55%)', NULL, NULL, 'receitas_e_investimentos'),
('receitas_e_investimentos_aluguel_imoveis', 'Aluguel de imóveis', '🏘️', 'hsl(150, 65%, 55%)', NULL, NULL, 'receitas_e_investimentos'),
('receitas_e_investimentos_outros_rendimentos', 'Outros rendimentos', '📝', 'hsl(150, 65%, 55%)', NULL, NULL, 'receitas_e_investimentos'),
('receitas_e_investimentos_cofrinho', 'Cofrinho', '🐷', 'hsl(150, 65%, 55%)', NULL, NULL, 'receitas_e_investimentos');